dist: xenial
     
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - sudo apt install apt-transport-https ca-certificates
  - echo "deb http://download.mono-project.com/repo/ubuntu stable-xenial/snapshots/5.20 main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  - sudo apt update
  - sudo apt install mono-devel
  - nuget restore
  
script:
  - csc NL2ControlPanel.sln
