language: csharp
mono: latest
dotnet: 3.1.201
solution: NL2ControlPanel.sln
install:
  - dotnet restore NL2ControlPanel.sln -Verbosity detailed
  - dotnet update NL2ControlPanel.sln -Verbosity detailed
