os: linux
language: csharp
solution: NL2ControlPanel.sln
mono: none
dotnet: 3.1.201

jobs:
  include:
    - os: linux
    dist: xenial
    scripts:
      - dotnet restore
      - dotnet build
    -os: linux
    dist: debian
    scripts:
      - dotnet restore
      - dotnet build
