dist: xenial
sudo: false
language: csharp

addons:
  apt:
    sources:
      - sourceline: deb http://download.mono-project.com/repo/ubuntu stable-xenial/snapshots/5.20 main
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
    packages:
      - mono-devel
      - ca-certificates-mono
     
before_install:
  - nuget restore
  
script:
  - csc NL2ControlPanel.sln
