version: 1.0.{build}

build:
  project: NL2ControlPanel.sln
  parallel: true
  verbosity: minimal
  publish_nuget: false
  publish_nuget_symbols: false

for:
-
  matrix:
    only:
      - image: Ubuntu
      
  build_script:
    - msbuild NL2ControlPanel.sln
